services:
  ros2-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_TAG: "24.04"
        ROS_DISTRO: "kilted"
        PROCESSING_VERSION: "4.4.10"
        PROCESSING_BUILD: "1310"
    image: ros2-p5-dev:kilted-local
    container_name: ros2-dev
    init: true
    restart: unless-stopped
    environment:
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - ./sketches:/ws/sketches
      - ./workspace:/ws
    ports:
      - "6080:6080" # For noVNC
      - "5900:5900" # For VNC