name: build-multiarch
on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write   # for pushing to GHCR

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/ros2-p5-dev
  ROS_DISTRO: kilted
  UBUNTU_TAG: "24.04"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (amd64, arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.ROS_DISTRO }}
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            ROS_DISTRO=${{ env.ROS_DISTRO }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
