name: build-multiarch
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: read

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/ros2-p5-dev
  PROCESSING_VERSION: "4.4.10"
  PROCESSING_BUILD: "1310"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ros: kilted
            ubuntu: "24.04"
            latest: true
          - ros: jazzy
            ubuntu: "24.04"
            latest: false
          - ros: humble
            ubuntu: "22.04"
            latest: false
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build
        env:
          BUILDKIT_PROGRESS: plain
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}:ci-${{ github.run_id }}-${{ matrix.ros }}
          labels: |
            org.opencontainers.image.title=ros2-p5-dev
            org.opencontainers.image.description=ROS2 ${{ matrix.ros }} + Processing ${{ env.PROCESSING_VERSION }} (linux/amd64, linux/arm64)
          build-args: |
            UBUNTU_TAG=${{ matrix.ubuntu }}
            ROS_DISTRO=${{ matrix.ros }}
            PROCESSING_VERSION=${{ env.PROCESSING_VERSION }}
            PROCESSING_BUILD=${{ env.PROCESSING_BUILD }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


