name: Build & Push (GHCR)

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros: [kilted, jazzy, humble]
        include:
          - ros: kilted
            latest: true
          - ros: jazzy
            latest: false
          - ros: humble
            latest: false

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute version (for tag builds)
        id: ver
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            RAW="${{ github.ref_name }}"     # v1.2.3
            echo "raw=$RAW" >> $GITHUB_OUTPUT
            echo "semver=${RAW#v}" >> $GITHUB_OUTPUT  # 1.2.3
          fi

      - name: Docker meta (compute tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=${{ matrix.ros }}
            type=raw,value=latest,enable=${{ matrix.latest && github.ref_type == 'branch' }}
            
      - name: Build & push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            UBUNTU_TAG=24.04
            ROS_DISTRO=${{ matrix.ros}}
            PROCESSING_VERSION=4.4.10
            PROCESSING_BUILD=1310
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
