name: release-please
on:
    push:
        branches: [ main ]
    workflow_dispatch: {}

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: googleapis/release-please-action@v4
              with:
                manifest-file: .release-please-manifest.json
                config-file: release-please-config.json
